function AND(a, b) {
  return a & b;
}
function OR(a, b) {
  return a | b;
}
function RSHIFT(a, b) {
  return a >> b;
}
function LSHIFT(a, b) {
  return a << b;
}

function memoize(fn) {
  const cache = new Map();

  return function (...args) {
    const key = JSON.stringify(args);
    if (cache.has(key)) {
      return cache.get(key);
    }
    const result = fn(...args);
    cache.set(key, result);
    return result;
  };
}

var c = () => 0;
var b = () => 956;
var ai = memoize(() => AND(af(), ah()));
var ll = memoize(() => ~lk());
var is_ = memoize(() => RSHIFT(hz(), 1));
var gp = memoize(() => ~go());
var dv = memoize(() => OR(du(), dt()));
var aa = memoize(() => RSHIFT(x(), 5));
var ba = memoize(() => OR(at(), az()));
var es = memoize(() => LSHIFT(eo(), 15));
var cu = memoize(() => OR(ci(), ct()));
var f = memoize(() => RSHIFT(b(), 5));
var fo = memoize(() => OR(fm(), fn()));
var ah = memoize(() => ~ag());
var x = memoize(() => OR(v(), w()));
var j = memoize(() => AND(g(), i()));
var ar = memoize(() => LSHIFT(an(), 15));
var cy = memoize(() => AND(1, cx()));
var jy = memoize(() => AND(jq(), jw()));
var ix = memoize(() => RSHIFT(iu(), 5));
var go = memoize(() => AND(gl(), gm()));
var bx = memoize(() => ~bw());
var jr = memoize(() => RSHIFT(jp(), 3));
var hj = memoize(() => AND(hg(), hh()));
var by = memoize(() => AND(bv(), bx()));
var et = memoize(() => OR(er(), es()));
var ks = memoize(() => OR(kl(), kr()));
var fm = memoize(() => RSHIFT(et(), 1));
var h = memoize(() => AND(e(), f()));
var ao = memoize(() => LSHIFT(u(), 1));
var hx = memoize(() => RSHIFT(he(), 1));
var ej = memoize(() => AND(eg(), ei()));
var bw = memoize(() => AND(bo(), bu()));
var eg = memoize(() => OR(dz(), ef()));
var ea = memoize(() => RSHIFT(dy(), 3));
var gn = memoize(() => OR(gl(), gm()));
var du = memoize(() => LSHIFT(da(), 1));
var aw = memoize(() => OR(au(), av()));
var gv = memoize(() => OR(gj(), gu()));
var fb = memoize(() => OR(eu(), fa()));
var ln = memoize(() => OR(lg(), lm()));
var g = memoize(() => OR(e(), f()));
var dn = memoize(() => ~dm());
var m = memoize(() => ~l());
var as_ = memoize(() => OR(aq(), ar()));
var gm = memoize(() => RSHIFT(gj(), 5));
var hp = memoize(() => AND(hm(), ho()));
var gi = memoize(() => LSHIFT(ge(), 15));
var ki = memoize(() => RSHIFT(jp(), 1));
var hi = memoize(() => OR(hg(), hh()));
var lw = memoize(() => LSHIFT(lc(), 1));
var ko = memoize(() => OR(km(), kn()));
var fk = memoize(() => LSHIFT(eq(), 1));
var an = memoize(() => AND(1, am()));
var hc = memoize(() => RSHIFT(gj(), 1));
var am = memoize(() => AND(aj(), al()));
var gw = memoize(() => AND(gj(), gu()));
var kr = memoize(() => AND(ko(), kq()));
var hb = memoize(() => OR(ha(), gz()));
var bz = memoize(() => OR(bn(), by()));
var jc = memoize(() => OR(iv(), jb()));
var ad = memoize(() => ~ac());
var bv = memoize(() => OR(bo(), bu()));
var l = memoize(() => AND(d(), j()));
var ce = memoize(() => LSHIFT(bk(), 1));
var dl = memoize(() => OR(de(), dk()));
var dw = memoize(() => RSHIFT(dd(), 1));
var im = memoize(() => AND(hz(), ik()));
var je = memoize(() => ~jd());
var fp = memoize(() => RSHIFT(fo(), 2));
var hv = memoize(() => LSHIFT(hb(), 1));
var lg = memoize(() => RSHIFT(lf(), 2));
var gl = memoize(() => RSHIFT(gj(), 3));
var kk = memoize(() => OR(ki(), kj()));
var al = memoize(() => ~ak());
var lf = memoize(() => OR(ld(), le()));
var ck = memoize(() => RSHIFT(ci(), 3));
var cd = memoize(() => AND(1, cc()));
var ky = memoize(() => ~kx());
var fw = memoize(() => OR(fp(), fv()));
var ey = memoize(() => AND(ev(), ew()));
var dx = memoize(() => LSHIFT(dt(), 15));
var ay = memoize(() => ~ax());
var bs = memoize(() => AND(bp(), bq()));
var ij = memoize(() => ~ii());
var cv = memoize(() => AND(ci(), ct()));
var ir = memoize(() => OR(iq(), ip()));
var y = memoize(() => RSHIFT(x(), 2));
var fs = memoize(() => OR(fq(), fr()));
var bq = memoize(() => RSHIFT(bn(), 5));
var k = memoize(() => OR(d(), j()));
var ab = memoize(() => OR(z(), aa()));
var gg = memoize(() => OR(gf(), ge()));
var dh = memoize(() => OR(df(), dg()));
var hk = memoize(() => ~hj());
var dj = memoize(() => ~di());
var fn = memoize(() => LSHIFT(fj(), 15));
var ly = memoize(() => RSHIFT(lf(), 1));
var p = memoize(() => AND(b(), n()));
var jx = memoize(() => OR(jq(), jw()));
var gq = memoize(() => AND(gn(), gp()));
var aq = memoize(() => RSHIFT(x(), 1));
var fa = memoize(() => AND(ex(), ez()));
var fd = memoize(() => ~fc());
var bk = memoize(() => OR(bj(), bi()));
var av = memoize(() => RSHIFT(as_(), 5));
var hy = memoize(() => LSHIFT(hu(), 15));
var gt = memoize(() => ~gs());
var fv = memoize(() => AND(fs(), fu()));
var dk = memoize(() => AND(dh(), dj()));
var cc = memoize(() => AND(bz(), cb()));
var er = memoize(() => RSHIFT(dy(), 1));
var he = memoize(() => OR(hc(), hd()));
var ga = memoize(() => OR(fo(), fz()));
var u = memoize(() => OR(t(), s()));
var d = memoize(() => RSHIFT(b(), 2));
var jz = memoize(() => ~jy());
var ia = memoize(() => RSHIFT(hz(), 2));
var kx = memoize(() => AND(kk(), kv()));
var gd = memoize(() => AND(ga(), gc()));
var gf = memoize(() => LSHIFT(fl(), 1));
var ca = memoize(() => AND(bn(), by()));
var hs = memoize(() => ~hr());
var bt = memoize(() => ~bs());
var lh = memoize(() => RSHIFT(lf(), 3));
var ax = memoize(() => AND(au(), av()));
var ge = memoize(() => AND(1, gd()));
var jt = memoize(() => OR(jr(), js()));
var fz = memoize(() => AND(fw(), fy()));
var ja = memoize(() => ~iz());
var t = memoize(() => LSHIFT(c(), 1));
var eb = memoize(() => RSHIFT(dy(), 5));
var br = memoize(() => OR(bp(), bq()));
var i = memoize(() => ~h());
var dt = memoize(() => AND(1, ds()));
var ae = memoize(() => AND(ab(), ad()));
var bj = memoize(() => LSHIFT(ap(), 1));
var bu = memoize(() => AND(br(), bt()));
var cb = memoize(() => ~ca());
var em = memoize(() => ~el());
var w = memoize(() => LSHIFT(s(), 15));
var gr = memoize(() => OR(gk(), gq()));
var fi = memoize(() => AND(ff(), fh()));
var kj = memoize(() => LSHIFT(kf(), 15));
var fx = memoize(() => AND(fp(), fv()));
var lj = memoize(() => OR(lh(), li()));
var bp = memoize(() => RSHIFT(bn(), 3));
var kb = memoize(() => OR(jp(), ka()));
var lx = memoize(() => OR(lw(), lv()));
var jb = memoize(() => AND(iy(), ja()));
var ek = memoize(() => OR(dy(), ej()));
var bi = memoize(() => AND(1, bh()));
var ku = memoize(() => ~kt());
var ap = memoize(() => OR(ao(), an()));
var ii = memoize(() => AND(ia(), ig()));
var ez = memoize(() => ~ey());
var cg = memoize(() => RSHIFT(bn(), 1));
var fl = memoize(() => OR(fk(), fj()));
var cf = memoize(() => OR(ce(), cd()));
var fc = memoize(() => AND(eu(), fa()));
var kh = memoize(() => OR(kg(), kf()));
var ju = memoize(() => AND(jr(), js()));
var iw = memoize(() => RSHIFT(iu(), 3));
var di = memoize(() => AND(df(), dg()));
var do_ = memoize(() => AND(dl(), dn()));
var le = memoize(() => LSHIFT(la(), 15));
var gh = memoize(() => RSHIFT(fo(), 1));
var gx = memoize(() => ~gw());
var gc = memoize(() => ~gb());
var jl = memoize(() => LSHIFT(ir(), 1));
var ak = memoize(() => AND(x(), ai()));
var hh = memoize(() => RSHIFT(he(), 5));
var lv = memoize(() => AND(1, lu()));
var fu = memoize(() => ~ft());
var gj = memoize(() => OR(gh(), gi()));
var li = memoize(() => RSHIFT(lf(), 5));
var z = memoize(() => RSHIFT(x(), 3));
var e = memoize(() => RSHIFT(b(), 3));
var hf = memoize(() => RSHIFT(he(), 2));
var fy = memoize(() => ~fx());
var jw = memoize(() => AND(jt(), jv()));
var hz = memoize(() => OR(hx(), hy()));
var kc = memoize(() => AND(jp(), ka()));
var fe = memoize(() => AND(fb(), fd()));
var il = memoize(() => OR(hz(), ik()));
var db = memoize(() => RSHIFT(ci(), 1));
var gb = memoize(() => AND(fo(), fz()));
var ft = memoize(() => AND(fq(), fr()));
var gk = memoize(() => RSHIFT(gj(), 2));
var ci = memoize(() => OR(cg(), ch()));
var ch = memoize(() => LSHIFT(cd(), 15));
var kg = memoize(() => LSHIFT(jm(), 1));
var ik = memoize(() => AND(ih(), ij()));
var fq = memoize(() => RSHIFT(fo(), 3));
var fr = memoize(() => RSHIFT(fo(), 5));
var fj = memoize(() => AND(1, fi()));
var la = memoize(() => AND(1, kz()));
var jh = memoize(() => AND(iu(), jf()));
var ct = memoize(() => AND(cq(), cs()));
var ep = memoize(() => LSHIFT(dv(), 1));
var hm = memoize(() => OR(hf(), hl()));
var kp = memoize(() => AND(km(), kn()));
var dm = memoize(() => AND(de(), dk()));
var dg = memoize(() => RSHIFT(dd(), 5));
var lp = memoize(() => ~lo());
var jv = memoize(() => ~ju());
var fh = memoize(() => ~fg());
var cp = memoize(() => AND(cm(), co()));
var ed = memoize(() => AND(ea(), eb()));
var df = memoize(() => RSHIFT(dd(), 3));
var gu = memoize(() => AND(gr(), gt()));
var eq = memoize(() => OR(ep(), eo()));
var cr = memoize(() => AND(cj(), cp()));
var lr = memoize(() => OR(lf(), lq()));
var ha = memoize(() => LSHIFT(gg(), 1));
var eu = memoize(() => RSHIFT(et(), 2));
var ji = memoize(() => ~jh());
var en = memoize(() => AND(ek(), em()));
var jo = memoize(() => LSHIFT(jk(), 15));
var ih = memoize(() => OR(ia(), ig()));
var gy = memoize(() => AND(gv(), gx()));
var fg = memoize(() => AND(et(), fe()));
var lk = memoize(() => AND(lh(), li()));
var ip = memoize(() => AND(1, io()));
var ke = memoize(() => AND(kb(), kd()));
var kn = memoize(() => RSHIFT(kk(), 5));
var ig = memoize(() => AND(id(), if_()));
var lt = memoize(() => ~ls());
var dy = memoize(() => OR(dw(), dx()));
var dq = memoize(() => AND(dd(), do_()));
var ls = memoize(() => AND(lf(), lq()));
var kd = memoize(() => ~kc());
var el = memoize(() => AND(dy(), ej()));
var kf = memoize(() => AND(1, ke()));
var ff = memoize(() => OR(et(), fe()));
var ic = memoize(() => RSHIFT(hz(), 5));
var dp = memoize(() => OR(dd(), do_()));
var cq = memoize(() => OR(cj(), cp()));
var dr = memoize(() => ~dq());
var ld = memoize(() => RSHIFT(kk(), 1));
var jj = memoize(() => AND(jg(), ji()));
var hq = memoize(() => OR(he(), hp()));
var hl = memoize(() => AND(hi(), hk()));
var ds = memoize(() => AND(dp(), dr()));
var eh = memoize(() => AND(dz(), ef()));
var ib = memoize(() => RSHIFT(hz(), 3));
var dd = memoize(() => OR(db(), dc()));
var iq = memoize(() => LSHIFT(hw(), 1));
var hr = memoize(() => AND(he(), hp()));
var cs = memoize(() => ~cr());
var lo = memoize(() => AND(lg(), lm()));
var hw = memoize(() => OR(hv(), hu()));
var io = memoize(() => AND(il(), in_()));
var ei = memoize(() => ~eh());
var hd = memoize(() => LSHIFT(gz(), 15));
var gs = memoize(() => AND(gk(), gq()));
var eo = memoize(() => AND(1, en()));
var kq = memoize(() => ~kp());
var ew = memoize(() => RSHIFT(et(), 5));
var lm = memoize(() => AND(lj(), ll()));
var hg = memoize(() => RSHIFT(he(), 3));
var ev = memoize(() => RSHIFT(et(), 3));
var bf = memoize(() => AND(as_(), bd()));
var cx = memoize(() => AND(cu(), cw()));
var ka = memoize(() => AND(jx(), jz()));
var o = memoize(() => OR(b(), n()));
var bh = memoize(() => AND(be(), bg()));
var hu = memoize(() => AND(1, ht()));
var gz = memoize(() => AND(1, gy()));
var ho = memoize(() => ~hn());
var cm = memoize(() => OR(ck(), cl()));
var ef = memoize(() => AND(ec(), ee()));
var lz = memoize(() => LSHIFT(lv(), 15));
var kv = memoize(() => AND(ks(), ku()));
var if_ = memoize(() => ~ie());
var hn = memoize(() => AND(hf(), hl()));
var s = memoize(() => AND(1, r()));
var ie = memoize(() => AND(ib(), ic()));
var ht = memoize(() => AND(hq(), hs()));
var ag = memoize(() => AND(y(), ae()));
var ee = memoize(() => ~ed());
var bm = memoize(() => LSHIFT(bi(), 15));
var dz = memoize(() => RSHIFT(dy(), 2));
var cj = memoize(() => RSHIFT(ci(), 2));
var bg = memoize(() => ~bf());
var in_ = memoize(() => ~im());
var ex = memoize(() => OR(ev(), ew()));
var id = memoize(() => OR(ib(), ic()));
var bo = memoize(() => RSHIFT(bn(), 2));
var de = memoize(() => RSHIFT(dd(), 2));
var bn = memoize(() => OR(bl(), bm()));
var bl = memoize(() => RSHIFT(as_(), 1));
var ec = memoize(() => OR(ea(), eb()));
var lq = memoize(() => AND(ln(), lp()));
var km = memoize(() => RSHIFT(kk(), 3));
var it = memoize(() => LSHIFT(ip(), 15));
var iu = memoize(() => OR(is_(), it()));
var iv = memoize(() => RSHIFT(iu(), 2));
var iy = memoize(() => OR(iw(), ix()));
var kl = memoize(() => RSHIFT(kk(), 2));
var cl = memoize(() => RSHIFT(ci(), 5));
var ma = memoize(() => OR(ly(), lz()));
var ac = memoize(() => AND(z(), aa()));
var jn = memoize(() => RSHIFT(iu(), 1));
var dc = memoize(() => LSHIFT(cy(), 15));
var cz = memoize(() => LSHIFT(cf(), 1));
var au = memoize(() => RSHIFT(as_(), 3));
var da = memoize(() => OR(cz(), cy()));
var a = memoize(() => lx());
var iz = memoize(() => AND(iw(), ix()));
var lu = memoize(() => AND(lr(), lt()));
var az = memoize(() => AND(aw(), ay()));
var jf = memoize(() => AND(jc(), je()));
var lb = memoize(() => LSHIFT(kh(), 1));
var lc = memoize(() => OR(lb(), la()));
var jk = memoize(() => AND(1, jj()));
var af = memoize(() => OR(y(), ae()));
var cn = memoize(() => AND(ck(), cl()));
var co = memoize(() => ~cn());
var kw = memoize(() => OR(kk(), kv()));
var kz = memoize(() => AND(kw(), ky()));
var cw = memoize(() => ~cv());
var kt = memoize(() => AND(kl(), kr()));
var jg = memoize(() => OR(iu(), jf()));
var jd = memoize(() => AND(iv(), jb()));
var jp = memoize(() => OR(jn(), jo()));
var js = memoize(() => RSHIFT(jp(), 5));
var jq = memoize(() => RSHIFT(jp(), 2));
var aj = memoize(() => OR(x(), ai()));
var bd = memoize(() => AND(ba(), bc()));
var be = memoize(() => OR(as_(), bd()));
var jm = memoize(() => OR(jl(), jk()));
var v = memoize(() => RSHIFT(b(), 1));
var r = memoize(() => AND(o(), q()));
var q = memoize(() => ~p());
var n = memoize(() => AND(k(), m()));
var at = memoize(() => RSHIFT(as_(), 2));
var bb = memoize(() => AND(at(), az()));
var bc = memoize(() => ~bb());

console.log(a());